Feature/e2e performance tests
defmethodinc/just-not-sorry pull request #184
Opened 2023-02-26 17:56 UTC by jduffy3

2023-02-27 20:43 UTC, sbrudz requested changes

2023-02-27 21:24 UTC, jduffy3 commented on src/components/JustNotSorry.js
> +    const parentRect = currentEmail.offsetParent.getBoundingClientRect();
Strange I'm not getting the above error and I tested via `npm run start:chrome` and loading the unpacked lib into my own browser... 😕

2023-02-27 21:41 UTC, sbrudz commented on src/components/JustNotSorry.js
> +    const parentRect = currentEmail.offsetParent.getBoundingClientRect();
That is strange.  I used the same command as you.

I first saw the error when I opened an email in my drafts folder after composing the first email (step 1).  Do you see the error if you try that as step 2?

Also, my `chrome://version` returns:

Google Chrome | 110.0.5481.100 (Official Build) (arm64)
-- | --
Revision | 4be7a36f7cb943af6118e449bbab494b43dcaddd-refs/branch-heads/5481_77@{#14}
OS | macOS Version 12.6.3 (Build 21G419)
JavaScript | V8 11.0.226.16
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36

What are you running?

2023-02-27 22:45 UTC, jduffy3 commented on src/components/JustNotSorry.js
> +    const parentRect = currentEmail.offsetParent.getBoundingClientRect();
Google Chrome | 110.0.5481.177 (Official Build) (arm64)
-- | --
Revision | f34f7ab2d4ca4ad498ef42aeba4f4eb2c1392d63-refs/branch-heads/5481@{#1239}
OS | macOS Version 13.0.1 (Build 22A400)
JavaScript | V8 11.0.226.16
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36


😕

2023-02-27 23:27 UTC, sbrudz commented on src/components/JustNotSorry.js
> +    const parentRect = currentEmail.offsetParent.getBoundingClientRect();
Yes, this is from Gmail.  I wouldn't think that the version of MacOS would make a difference, but maybe...?

2023-02-28 13:54 UTC, jduffy3 commented on src/components/JustNotSorry.js
> +    const parentRect = currentEmail.offsetParent.getBoundingClientRect();
Not sure :( I pushed up a change that checks that its not null or undefined on the ref and added some setup scripts around modifying the manifest 🙏

2023-02-28 17:19 UTC, jduffy3 commented
Thanks @sbrudz  the video was super helpful. So the offset parent is null when the message gets minimized when composing a new email. My window was wide enough to keep the two messages open, that's why it wasn't failing!

2023-03-01 00:49 UTC, sbrudz approved these changes
I didn't think about window size being a factor.  The fix looks good.  No more errors.  Thank you!  :shipit:

2023-03-01 13:09 UTC, merged